<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNodeCategory(Category $category)
    {
        $categories = $this->_em->getRepository(Category::class)->getTree($category);
        $qb = $this->_em->createQueryBuilder('p')->from(Post::class,'p');
        return $qb
            ->select('p')
            ->where('p.category IN (:categories)')
            ->setParameter('categories',$categories)
            ->getQuery()->getArrayResult();
    }
}
