fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Config/routing.yml"

_welcome:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /blog
        permanent: true
