# 首页路由跳转到博客文章展示页
_welcome:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /blog
        permanent: true
#前端控制器路由
frontend:
    resource: "@AppBundle/Controller/Frontend"
    type:     annotation
    prefix: /

frontend_widget:
    resource: "@AppBundle/Widget/Frontend"
    type:     annotation
    prefix: /widget

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

#fos_comment_api:
#   type: rest
#   resource: "@FOSCommentBundle/Resources/config/routing.yml"
#   prefix: /api
#   defaults: { _format: html }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"