services:
    # 注册Markdown类为服务
    markdown:
        class: AppBundle\Utils\Markdown

    # 注册Markdown的Twig过滤器
    twig.markdown.extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        tags:
            - { name: twig.extension }

    # widget的服务配置
    widget.app.blog_breadcurmb:
        class: AppBundle\Widget\Frontend\Blog\BreadcrumbWidget
        arguments: ['@service_container']

    widget.app.blog_sidemenu:
        class: AppBundle\Widget\Frontend\Blog\SideMenuWidget
        arguments: ['@service_container']

    widget.app.blog_navmenu:
        class: AppBundle\Widget\Frontend\Blog\NavMenuWidget
        arguments: ['@service_container']