services:
    # 注册Markdown类为服务
    markdown:
        class: AppBundle\Utils\Markdown

    pingyin:
        class: AppBundle\Utils\ToPingyin

    sluger:
        class: AppBundle\Utils\Sluger
        arguments: ['@pingyin']

    # 注册Markdown的Twig过滤器
    twig.markdown.extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        tags:
            - { name: twig.extension }

    doctrine.pingyin_slug.subscriber:
        class: AppBundle\EventListener\PingyinSlugSubscriber
        arguments: ['@pingyin']
        tags:
            - { name: doctrine.event_subscriber }
    widget.app.blog_category:
        class: AppBundle\Widget\Frontend\Blog\CategoryWidget
        arguments: ['@service_container']

    widget.app.blog_breadcurmb:
        class: AppBundle\Widget\Frontend\Blog\BreadcrumbWidget
        arguments: ['@service_container']

    widget.app.blog_nav:
        class: AppBundle\Widget\Frontend\Blog\NavWidget
        arguments: ['@service_container']